---

- name: install Sense plugin
  action: >
    shell bin/kibana plugin --install elastic/sense
    chdir={{ kibana_install_dir }}/kibana-{{ kibana_version }}-linux-x64/

# Fix permissions
- file: >
    path="{{ kibana_install_dir }}/kibana-{{ kibana_version }}-linux-x64/installedPlugins/sense" state=directory
    owner={{ kibana_user }} group={{ kibana_group }}
    recurse=yes
  sudo: true